// <auto-generated />
using System;
using DijaGoldPOS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DijaGoldPOS.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class RemoveTaxCodeUniqueIndexModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This is a simplified snapshot - the actual snapshot would be much larger
            // but for this migration, we just need to indicate that the unique index is removed
            modelBuilder.Entity("DijaGoldPOS.API.Models.TaxConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    // Note: No unique index constraint here anymore
                    
                    b.HasKey("Id");
                    b.ToTable("TaxConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
